[package]
name = "linura-hardware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-core = { path = "../linura-core" }
linura-observation = { path = "../linura-observation" }

[lints]
workspace = true
