[package]
name = "linura-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-capability-sdk = { path = "../linura-capability-sdk" }
linura-core = { path = "../linura-core" }
linura-dbus = { path = "../linura-dbus" }
linura-graph = { path = "../linura-graph" }
linura-intent = { path = "../linura-intent" }
linura-library = { path = "../linura-library" }
linura-observation = { path = "../linura-observation" }
linura-protocol = { path = "../linura-protocol" }
linura-provenance = { path = "../linura-provenance" }

[lints]
workspace = true
