[package]
name = "linura-linux-observation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-io = "2.6"
futures-lite = "2.6"
linura-core = { path = "../linura-core" }
linura-observation = { path = "../linura-observation" }
linura-provider-sdk = { path = "../linura-provider-sdk" }
rustix = { version = "1.1", features = ["event", "net", "system"] }
zbus = { version = "=5.19.0", default-features = false, features = ["async-io", "blocking-api"] }

[lints]
workspace = true
